name: Deploy wasm with Dagger

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  release:
    runs-on: [self-hosted, linux, x64]
    env:
      DAGGER_ENGINE: container+podman://dagger-engine-v1.0.0-beta.13

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Build WASM
        run: |
          "$HOME/.local/bin/dagger" -M api call \
            container \
            from --address=golang:1.27.1 \
            with-directory --path=/src --source=. --exclude=build \
            with-workdir --path=/src \
            with-env-variable --name=GOOS --value=js \
            with-env-variable --name=GOARCH --value=wasm \
            with-env-variable --name=GOEXPERIMENT --value=simd \
            with-exec --args=go,build,-o,dicewillroll.wasm,. \
            file --path=/src/dicewillroll.wasm \
            export --path="$HOME/prod/ebiten-wasm/wasms/dicewillroll/latest.wasm"
