name: Deploy wasm with Dagger

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  release:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v5
      - name: Build WASM

  run: |
    "$HOME/.local/bin/dagger" -m core api call \
      container \
      from --address=golang:1.27.1 \
      with-directory --path=/src --source=. --exclude=build \
      with-workdir --path=/src \
      with-new-directory --path=/out \
      with-env-variable --name=GOOS --value=js \
      with-env-variable --name=GOARCH --value=wasm \
      with-exec --args=go,build,-o,/out/dicewillroll.wasm,. \
      file --path=/out/dicewillroll.wasm \
      export --path="$HOME/prod/ebiten-wasm/wasms/dicewillroll/latest.wasm"
